name: Iso Add Virtro

on:
  push:
    branches:
      - main

jobs:
  download-and-verify:
    runs-on: ubuntu-latest

    env:
      FILE_HASH: "C117C5DDBC51F315C739F9321D4907FA50090BA7B48E7E9A2D173D49EF2F73A3"
      FILE_MAGNET_LINK: "magnet:?xt=urn:btih:366ADAA52FB3639B17D73718DD5F9E3EE9477B40&dn=SW_DVD9_WIN_ENT_LTSC_2021_64BIT_ChnSimp_MLF_X22-84402.ISO&xl=5044211712"
      FILE_PATH: "/tmp/isopath"
      FILE_NAME: "SW_DVD9_WIN_ENT_LTSC_2021_64BIT_ChnSimp_MLF_X22-84402.ISO"
      DHT_DOWNLOAD_URL: "https://aria2-conf-i5fd5w2el-p3terx.vercel.app/dht.dat"
      TRACK_DOWNLOAD_URL: "https://cf.trackerslist.com/best_aria2.txt"
      VIRTRO_DOWNLOAD_URL: "https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/latest-virtio/virtio-win.iso"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install software
      run: |
        sudo apt-get install aria2
        sudo apt install xorriso

    - name: Mkdir
      run: |
        sudo mkdir $FILE_PATH
        sudo mkdir /mnt/virtroiso

    - name: Download Win.iso with aria2
      if: ${{ env.FILE_MAGNET_LINK != '' }}
      run: |
        echo  ${{ env.FILE_MAGNET_LINK}}
        sudo wget -P /root/.cache/aria2/ $DHT_DOWNLOAD_URL
        sudo wget $TRACK_DOWNLOAD_URL
        sudo aria2c --dir=$FILE_PATH --seed-time=0 --seed-ratio=1.0 --dht-entry-point=dht.transmissionbt.com:6881 --bt-tracker=$(cat best_aria2.txt) --check-certificate=false -s8 -x16 "$FILE_MAGNET_LINK"


    - name: Download Virtro.iso with aria2
      run: |
        sudo wget  $VIRTRO_DOWNLOAD_URL -O $FILE_PATH/virtro.iso
        sudo mount -o loop $FILE_PATH/virtro.iso /mnt/virtroiso
        echo $(ls $FILE_PATH)

    - name: Verify hash
      if: ${{ env.FILE_MAGNET_LINK != '' }}
      run: |
        cd $FILE_PATH
        echo "$FILE_HASH *$FILE_NAME" | sha256sum --check -
        echo $(ls $FILE_PATH)

    - name: Make New Iso with Virtro
      run: |
        cd $FILE_PATH
        sudo xorriso -as mkisofs -o win_with_virtro.iso -isohybrid-mbr $FILE_NAME -graft-points /mnt/virtroiso /
      
    - name: Upload to Gofile.io
      uses: ahnafnafee/action-upload-gofile@v2.1.0
      with:
        file: /tmp/isopath/win_with_virtro.iso
        token: ${{ secrets.GOFILE_APIKEY }}
          
